sonata_admin:
    title: 'Exozet CMS'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: right }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
contexts: [admin]
